Client again
Questspace-v2/questspace-frontend pull request #2
Opened 2023-10-20 17:11 UTC by RedSquid2212

Непонятки с параметрами для create и update

2023-10-20 17:18 UTC, BasedDepartment1 requested changes

2023-10-20 17:18 UTC, BasedDepartment1 commented on app/api/client-handler.ts
> +    hello: async function hello() {
Понимаю что это тестовая штука, но тс вообще переваривает нетипизированные функции?

2023-10-20 17:18 UTC, BasedDepartment1 commented on app/api/client.ts
> +            .catch(reason => console.error(`Error while fetching: ${reason}`));
На этом этапе ошибка проглотится или выбросится дальше?

2023-10-20 17:18 UTC, BasedDepartment1 commented on app/api/custom-errors.ts
> +class HttpError extends Error {
Во всем этом файле отступы два пробела, а в остальных 4

2023-10-20 17:18 UTC, BasedDepartment1 commented on app/api/client-handler.ts
> +    updateUser: async function updateUser(
Код точно отработает нормально по точму что касается типов? Потому что поля в json отличаются от имен в интерфейсе, надо добавить then с возвратом интерфейса из полей наверное

2023-10-20 17:19 UTC, cutletmedie commented
Я, если честно, вообще не поняла, как к тебе в ветку попали мои прямые коммиты в мейн, но ладно. Косяк не твой.

2023-10-20 17:22 UTC, cutletmedie commented on app/api/client-handler.ts
> +    hello: async function hello() {
Скажем так, он может закрыть глаза, если ты не указал типы, но тут тоже должен промис возвращаться, ща подумаю какой

2023-10-20 17:29 UTC, RedSquid2212 commented on app/api/client-handler.ts
> +    hello: async function hello() {
Он может вывести возвращаемый тип самостоятельно

2023-10-20 17:37 UTC, RedSquid2212 commented on app/api/client.ts
> +            .catch(reason => console.error(`Error while fetching: ${reason}`));
The console.error() method outputs an error message to the Web console

Как будто бы должна проглотиться

2023-10-20 18:16 UTC, BasedDepartment1 commented on app/api/client.ts
> +            .catch(reason => console.error(`Error while fetching: ${reason}`));
А после catch? Лог ясно что ничего не делает

2023-10-25 11:43 UTC, RedSquid2212 commented on app/api/client.ts
> +            .catch(reason => console.error(`Error while fetching: ${reason}`));
Проглотится

2023-10-25 12:10 UTC, BasedDepartment1 commented on app/api/client-handler.ts
> +    updateUser: async function updateUser(
До сих пор не вижу фикса вот этого коммента

2023-10-25 13:40 UTC, RedSquid2212 commented on app/api/client.ts
> +            .catch(reason => console.error(`Error while fetching: ${reason}`));
Окей, просто кинуть ошибку в самом кэтче

2023-10-25 13:41 UTC, RedSquid2212 commented on app/api/client-handler.ts
> +    updateUser: async function updateUser(
М, такс, а можно чуть подробнее объяснить, что тут должно быть?

2023-10-25 13:41 UTC, RedSquid2212 commented on app/api/client-handler.ts
> +            `/user`,
Окес, заменю)

2023-10-25 13:42 UTC, RedSquid2212 commented on app/api/client-handler.ts
> +        return response as IUserAuth;
Передавать как дженерик-параметр IUserAuth?

2023-10-25 13:46 UTC, BasedDepartment1 commented on app/api/client-handler.ts
> +        return response as IUserAuth;
`response.json as T` подойдет?

2023-10-25 13:48 UTC, BasedDepartment1 commented on app/api/client-handler.ts
> +        return response as IUserAuth;
Пардон, тут меня не туда понесло, лучше уйдем в осуждение выше

2023-10-25 13:49 UTC, BasedDepartment1 commented on app/api/client-handler.ts
> +    updateUser: async function updateUser(
Условное поле `avatar_url` из json вряд ли само по себе запихнется в поле `avatarUrl` интерфейса, поэтому может на этом этапе самостоятельно конструировать приходящий объект из полей json?

2023-11-04 09:45 UTC, BasedDepartment1 approved these changes

2023-11-05 14:34 UTC, cutletmedie approved these changes

2023-11-05 14:35 UTC, merged